strawberry_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: StrawberryHelloBundle:Default:index }
    
strawberry_add_page:
    pattern:  /add/
    defaults: { _controller: StrawberryHelloBundle:Default:add }
